theme: jekyll-theme-minimal
title: Phat's blog
description: Tech blog
show_downloads: false
permalink: /:categories/:title/
excerpt_separator: <!--more-->
paginate: 10
plugins:
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag
   - jekyll-avatar
   - jekyll-mentions
